### ISSUE TITLE
Don't reconnect st2 DB/MQ on failure, exit early instead

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#10]
> Cloned from https://github.com/StackStorm/st2enterprise-dockerfiles/issues/57

The current/default StackStorm tries to reconnect to Mongo or RabbitMQ on failure.
This is undesired behavior in K8s environment where engine handles failover by rescheduling exited container.
So the desired configuration is to exit fast any st2 service on failure without reconnection and let K8s handle it.

Luckily, these settings are configurable in `st2.conf`: 
https://github.com/StackStorm/st2/blob/master/conf/st2.conf.sample#L179
https://github.com/StackStorm/st2/blob/master/conf/st2.conf.sample#L109

Hardcode them in default `st2.conf` (during the Docker image build or/and in K8s objects) to not reconnect, but exit st2 on failure.

**Comment by warrenvw** [comment]
Resolved by https://github.com/StackStorm/st2-dockerfiles/pull/12.
