### ISSUE TITLE
Ingress servicePort is defined as String

### ISSUE THREAD

**Issue by erenatas** [StackStorm/stackstorm-ha#110]
I believe I have missed this one. 

https://github.com/StackStorm/stackstorm-ha/blob/ff078b22af1e31b175957938d11405b3163778d1/templates/ingress.yaml#L43

Should not be defined as a string, which results in the following error:

```
helm install test .
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: Ingress.extensions "test-ingress" is invalid: spec.rules[0].http.backend.servicePort: Invalid value: "80": must contain at least one letter or number (a-z, 0-9)
```

**Comment by armab** [comment]
Is this with Helm 3.0?

**Comment by erenatas** [comment]
> Do you get this error with Helm 3.0?

Yes.

**Comment by armab** [comment]
OK, stackstorm-ha doesn't officially support Helm 3 yet, but future fixes like that would be nice to have!
