### ISSUE TITLE
Add custom annotations to Sensorcontainer and Actionrunner Pods 

### ISSUE THREAD

**Issue by stefangusa** [StackStorm/stackstorm-ha#122]
For example, if there are actions to be performed in AWS or events to be retrieved from AWS, the `actionrunner` Pods or the `sensorcontainer` Pods require a IAM role attached to them, in annotations:

`iam.amazonaws.com/role: <Role_ARN>`

This is just a use case for adding a custom annotation to one or more Pods. I think the chart should support such behaviour.

**Comment by armab** [comment]
This could be done by attaching IAM roles for service accounts.
It's implemented in https://github.com/StackStorm/stackstorm-ha/pull/117

See https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html for more info about how to use it.

**Comment by stefangusa** [comment]
I have configured the IAM role way before this new feature using a new annotation and I thought I could extend this to other functionalities. If you don't find any use case, I think the issue may be closed.

**Comment by armab** [comment]
Alright, I left a few review comments in PR to get the enhancement merged.

**Comment by stefangusa** [comment]
I have made an update taking into consideration your recommandations.
