### ISSUE TITLE
Start mongodb with --auth option

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/stackstorm-ha#13]
> Moved from StackStorm/st2enterprise-dockerfiles#62

It is not recommended to run mongodb without authentication, for any length of time.

Some useful references:

 - https://www.mongodb.com/blog/post/running-mongodb-as-a-microservice-with-docker-and-kubernetes
 - http://pauldone.blogspot.com/2017/06/deploying-mongodb-on-kubernetes-gke25.html
 - https://www.serverlab.ca/tutorials/linux/database-servers/how-to-create-mongodb-replication-clusters/

Chart has `auth` section to configure: https://github.com/helm/charts/tree/master/stable/mongodb-replicaset#authentication so should be doable with Helm `values.yaml`.

**Comment by armab** [comment]
Implemented via https://github.com/StackStorm/stackstorm-ha/pull/63
