### ISSUE TITLE
No python3.6 found (Only 3.5 & 2.7 are installed)  

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/stackstorm-ha#130]
Hi, 

I'm migrating my packs from standalone stackstorm to HA cluster but my action/workflow fails due to python3.6 not found for action runner and it tries to run with v2.7.

If I mention python==3.6.8 inside requirements.txt while building image then docker build doesn't work, it says package didn't find.
Used https://github.com/StackStorm/st2packs-dockerfiles to install custom image.

**My st2client pod:**
```
root@rafting-nightingale-st2client-6c4545c5c7-ms6jc:/opt/stackstorm# python
python2.7   python3     python3.5   python3.5m  python3m
```

Please help!

**Comment by armab** [comment]
At the moment stackstorm-ha works only with python 2.
Please follow the https://github.com/StackStorm/stackstorm-ha/pull/129 which describes plan about python 3 as a base image for stackstorm-ha Helm chart.
