### ISSUE TITLE
Install pods in different namespace

### ISSUE THREAD

**Issue by sachinyadavg** [StackStorm/stackstorm-ha#133]
Hi Team,

How can I install pods in a given namespace and not just default. I tried finding in yaml files but couldn't find anything related.
Thanks in advance!

**Comment by armab** [comment]
Check the `helm install --help` which allows settings a chart installation in specific namespace.

**Comment by manisha-tanwar** [comment]
Thanks @armab It worked!!

**Comment by sachinyadavg** [comment]
Thanks @armab It worked!!
