### ISSUE TITLE
Install chart with tillerless helm

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/stackstorm-ha#135]
Hi Team,

Is it possible to install this stackstorm-ha chart on helm with tillerless plugin?
Getting below error while trying to install it.

`Error: release garish-swan failed: roles.rbac.authorization.k8s.io is forbidden: User "oidc:manisha.tanwar" cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "stackstorm-test"`

Followed `https://github.com/rimusz/helm-tiller` to install tillerless plugin.

Any help would be appreciated! Thanks!

**Comment by armab** [comment]
Can you elaborate more about tillerless and how it can affect normal Helm 2 installation/configuration?
Or do you mean Helm 3 #98 which comes with no Tiller?

**Comment by manisha-tanwar** [comment]
Hi @armab I installed tiller using https://github.com/rimusz/helm-tiller

where we do helm init --client-only

**Comment by manisha-tanwar** [comment]
Sorry for responding too late but yes it was related to permission error.

**Comment by armab** [comment]
Thanks for responding anyways where the issue was!
