### ISSUE TITLE
Unable to decrypt the secret values from data store for rule. st2schedular not mounting "st2-encryption-key-vol" volume.

### ISSUE THREAD

**Issue by rahulshinde26** [StackStorm/stackstorm-ha#147]
Getting below error in st2 schedular when trying to access the secret from st2kv with decryptkv.

{
  "error": "Failed to render parameter \"password\": [Errno 2] No such file or directory: '/etc/st2/keys/datastore_key.json'",
  "traceback": "  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/enforcer.py\", line 201, in _invoke_action
    additional_contexts=additional_contexts)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/enforcer.py\", line 83, in get_resolved_parameters
    additional_contexts=additional_contexts)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py\", line 311, in render_live_params
    context = _resolve_dependencies(G)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py\", line 228, in _resolve_dependencies
    raise ParamException(msg)
"
}

**Comment by armab** [comment]
Thanks for the report!

Can you provide the full unstripped log?
How did you find it’s happening in st2scheduler?

**Comment by rahulshinde26** [comment]
This is the only log I see on UI.

This was happening when I was trying to schedule a WF using intervaltimer for every 30 minutes.
If I execute action manually it works fine, but when triggered through the rule using intervaltimer, it results in above error.
I am passing the parameters to action using st2kv which are encrypted. Non- encrypted parameters are passed properly without any issue.

**Comment by rahulshinde26** [comment]
This is the rule i was creating. decrypt_kv is causing the error mentioned in this issue.
`---
  name: "scheduler_rule"                     
  pack: "my_pack"                       
  description: "Calls my wf repeatitively every 10 minutes"       
  enabled: true                          
  trigger:
    type: "core.st2.CronTimer"
    parameters:
      timezone: "UTC"
      minute: 0/10
  action:                                
    ref: "my_pack.scheduler_master"
	parameters:
      host: "{{ st2kv.system.host }}"
      username: "{{ st2kv.system.username }}"
      password: "{{ st2kv.system.password | decrypt_kv }}"`

**Comment by armab** [comment]
Thanks for more details, this clarifies the issue very well now.

**Comment by DavidMeu** [comment]
@rahulshinde26 Regarding that issue.

Where you able to get the DS value after that fix?
I'm facing that the basic scenario is not working:
https://github.com/StackStorm/st2/issues/5260
