### ISSUE TITLE
Replace external dependency charts from viable repo as stable repo charts are getting deprecated

### ISSUE THREAD

**Issue by arms11** [StackStorm/stackstorm-ha#154]
Charts from stable repo backed by google apis are being removed and are getting deprecated. 
The recommended replacements are [bitnami charts](https://github.com/bitnami/charts/tree/master/bitnami)

3 of 4 charts are part of the deprecation:
Rabbitmq-ha: https://github.com/helm/charts/tree/master/stable/rabbitmq-ha
Mongodb-replicaset: https://github.com/helm/charts/tree/master/stable/mongodb-replicaset
External-DNS: https://github.com/helm/charts/tree/master/stable/external-dns

Recommended replacement:
RabbitMQ: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
MongoDB: https://github.com/bitnami/charts/tree/master/bitnami/mongodb
External-DNS: https://github.com/bitnami/charts/tree/master/bitnami/external-dns

Please Note: Several parameters (values) used by the replacement charts are a bit different. (i.e. Rabbitmq password for admin user is 24 characters in stable while in bitnami it's 10.)

**Comment by armab** [comment]
Thanks for tracking and reporting this! 

If someone willing to contribute the migration to new helm chart dependencies, - that's a good first issue, help wanted.
