### ISSUE TITLE
Use internal K8's ETCD instead of creating new ETCD pods for StackStorm HA

### ISSUE THREAD

**Issue by te4336** [StackStorm/stackstorm-ha#156]
With Kubernetes already deploying ETCD as a datastore on all of it's master nodes it doesn't make much sense to have to spin up another set of ETCD pods within the cluster. There should be an option to disable the creation of the ETCD pods in the values.yaml file and instead use the ETCD pods that are already in use on the kubernetes cluster.

**Comment by ericreeves** [comment]
I've spent literally zero minutes researching this, but will this work with EKS driving Kubernetes 1.17?

I don't want to use kops.  :)

**Comment by armab** [comment]
Did you check the existing Helm values?


There is already an option to disable the `etcd` cluster creation:
https://github.com/StackStorm/stackstorm-ha/blob/c2e767cf1cde955237f49afb3a8417c05bdfbb43/values.yaml#L475-L485

This was implemented a while ago https://github.com/StackStorm/stackstorm-ha/pull/127.
