### ISSUE TITLE
st2rulesengine references datastore_crypto_key incorrectly

### ISSUE THREAD

**Issue by lordpengwin** [StackStorm/stackstorm-ha#188]
I'm seeing a problem where the st2rulesengine is getting hung in the Init:0/2 state and I believe it is waiting for the wrong name. The rest of the entries in the deployments.yaml file have this:

>        {{- if .Values.secrets.st2.datastore_crypto_key }}
>        - name: st2-encryption-key-vol
>          secret:
>            secretName: {{ .Release.Name }}-st2-datastore-crypto-key
>            items:
>            - key: datastore_crypto_key
>              path: datastore_key.json
>        {{- end }}

where as the rulesengine has this:

>        {{- if .Values.secrets.st2.datastore_crypto_key }}
>        - name: st2-encryption-key-vol
>          secret:
>            secretName: datastore_crypto_key
>            items:
>            - key: datastore_crypto_key
>              path: datastore_key.json
>        {{- end }}

Note the difference in secretName.

The strange thing is that it works sometimes

**Comment by armab** [comment]
Yeah, looks like a bug. Can you please submit a PR to fix this?

**Comment by lordpengwin** [comment]
I created a PR for this: https://github.com/StackStorm/stackstorm-ha/pull/190

Note: I also noticed that -st2sensorcontainer references it differently as the following:

_secretName: {{ $.Release.Name }}-st2-datastore-crypto-key_

I did not change it because I do not know enough about helm to understand if this is a problem.

**Comment by armab** [comment]
Fixed by https://github.com/StackStorm/stackstorm-ha/pull/190
