### ISSUE TITLE
<ST2 on k8s> Unable to decrypt the secret values from data store when used in webhook. st2rulesengine not mounting "st2-encryption-key-vol" volume.

### ISSUE THREAD

**Issue by moti1992** [StackStorm/stackstorm-ha#223]
**Webhook rule under rules/:**

```
---
name: "wb"
pack: "xxx"
description: "Sample webhook to remote cmd run"
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: remote
criteria:
  trigger.body.name:
    pattern: "run"
    type: "equals"
action:
  ref: "xxx.yyy"
  parameters:
    cmd: "{{trigger.body.cmd}}"
```

**Getting the below error on rulesengine pod:**

```
error: 'Failed to render parameter "username": [Errno 2] No such file or directory: ''/etc/st2/keys/datastore_key.json'''
  traceback: "  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/enforcer.py", line 237, in _invoke_action
    additional_contexts=additional_contexts,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/enforcer.py", line 83, in get_resolved_parameters
    additional_contexts=additional_contexts,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 334, in render_live_params
    context = _resolve_dependencies(G)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 242, in _resolve_dependencies
    raise ParamException(msg)
"
```

**Comment by cognifloyd** [comment]
What version of the StackStorm-ha chart are you using?
What version of StackStorm?

**Comment by moti1992** [comment]
I'm using the code pulled from master in the past month. Pulled from this Commit ID: 2f9d0c9c7470f6798733929b55f55bb3f02a926f

ST2 version:
st2 3.5.0, on Python 3.6.9

Moreover, I have tried mounting the datastore on st2rulesengine (below image) and it worked after that. Just wanted to confirm if its a right fix or not. Please review and let me know if further info needed. 

<img width="858" alt="Screenshot 2021-07-22 at 9 35 59 PM" src="https://user-images.githubusercontent.com/4049727/126671581-6b6fd075-908d-4fe1-8df7-46306f259027.png">

**Comment by copart-jafloyd** [comment]
Let's see. So right now we're adding a datastore_crypto_key `volume` in these deployments:
- st2api
- st2rulesengine
- st2workflowengine
- st2scheduler
- st2sensorcontainer
- st2actionrunner
- st2client

But we're only mounting the volume in these:
- st2api
- st2workflowengine
- st2scheduler
- st2sensorcontainer
- st2actionrunner
- st2client

So, yes. We are missing the volumeMount for the `st2rulesengine`. Would you please submit a PR? Thanks for finding a fix for this!

**Comment by cognifloyd** [comment]
Let's see. So right now we're adding a datastore_crypto_key `volume` in these deployments:
- st2api
- st2rulesengine
- st2workflowengine
- st2scheduler
- st2sensorcontainer
- st2actionrunner
- st2client

But we're only mounting the volume in these:
- st2api
- st2workflowengine
- st2scheduler
- st2sensorcontainer
- st2actionrunner
- st2client

So, yes. We are missing the volumeMount for the `st2rulesengine`. Would you please submit a PR? Thanks for finding a fix for this!

**Comment by moti1992** [comment]
Sure I will raise a PR. Thanks for the confirmation.

**Comment by moti1992** [comment]
@cognifloyd  getting this error when i tried to commit to new branch from master
ERROR: Permission to StackStorm/stackstorm-ha.git denied to moti1992.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

Is there any permission required ?

**Comment by moti1992** [comment]
@cognifloyd  PR : https://github.com/StackStorm/stackstorm-ha/pull/224
