### ISSUE TITLE
Fix indentation for ServiceAccount pullSecrets

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/stackstorm-ha#227]
I had the indentation wrong for `imagePullSecrets` in #196 

I have a branch prepared to fix it: https://github.com/cognifloyd/stackstorm-ha/tree/fix-sa-pullsecret
I will submit a PR later.

**Comment by armab** [comment]
It would be really nice to go directly with the PR creation here, considering 2 lines change bugfix.

**Comment by cognifloyd** [comment]
I'm juggling a lot of branches. I want to finish polishing additional PRs after the current sensor PRs are merged.

I submitted the issues to make sure they don't get lost, and to make sure we don't make a release without including at least the bug fixes.
