### ISSUE TITLE
Feature: Allow hook/jobs to use an st2 api_key instead of user/pass

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/stackstorm-ha#233]
ST2 uses LDAP for auth in my environment. But, I can't add `st2admin` and similar service account users to LDAP. So, the service accounts need to authenticate with an st2 api key when communicating with the st2 api.

To facilitate using this, at least for upgrades, I need to be able to add the api_key to the jobs via values.

I have a branch prepared to add this feature: https://github.com/cognifloyd/stackstorm-ha/tree/jobs_api_key
I will submit a PR later.

**Comment by armab** [comment]
Yeah, we've created the st2admin user in LDAP and referenced its username/password in the Helm values in the past.

Looking at the code, adding a corner case to the upstream Chart when a dedicated API key is referenced (to be used only for upgrade) to run the `job-st2-apikey-load` is too much of a hack for the upstream chart!

Considering you can't create st2admin user in your org LDAP, maybe overriding the Job itself in the custom environment with a parent chart for such a special case would work?
