### ISSUE TITLE
Feature: Allow users to define custom helm hook jobs to run on install/upgrade/etc

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/stackstorm-ha#234]
Related to #233, I need to be able to generate an api_key on install before any of the other helm hook jobs run.
I also need to run a workflow to save the enabled/disabled state of aliases before an upgrade, and restore them after an upgrade.
Ideally, helm should kick off those tasks.

Helm hooks can be applied to many k8s objects, but I only need to run Jobs, so I think we should offer a very narrow way to define hook jobs without going to the trouble of creating a parent chart.

I have a branch prepared to add this `jobs.extra_hooks` feature: https://github.com/cognifloyd/stackstorm-ha/tree/jobs_extra_hooks
I will submit a PR later.

**Comment by armab** [comment]
Yeah, I think the use of subchart <> parent chart is the best approach here.

It's, in fact, one of the good practices that'll give you more benefits and flexibility besides of infra-as-code version pinning and is recommended by the https://github.com/StackStorm/stackstorm-ha#extending-this-chart. https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by cognifloyd** [comment]
I don't think a "subchart <> parent chart" is a good approach in this case.

From the description of #265:
> There is a lot of boilerplate for custom StackStorm hook-jobs. That boilerplate is likely to become out-of-date as we refine the chart, so managing that boilerplate within this chart alongside our other jobs would be ideal.
>
> Since there is so much chart-specific boilerplate, parent charts would have to depend on a lot of implementation details making them very brittle. Parent charts are much better suited to jobs that don't need access to most of the packs, configs, configmaps, and secrets that this chart provides.
