### ISSUE TITLE
Feature: Allow serving https from the st2web pod

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/stackstorm-ha#236]
Currently we have the st2web pods serving HTTP.
In our environment, we have another nginx instance that is the primary entry point for the domain associated with st2. This nginx host is outside the k8s cluster and then forwards the traffic to the st2web pods in the cluster.
I want the traffic going into the cluster to also be HTTPS, though I'm fine with a generated certificate.

I have a branch prepared to add this feature: https://github.com/cognifloyd/stackstorm-ha/tree/st2web-https
My branch allows people to enable HTTPS in st2web, and if an `ssl_certificate` + `ssl_certificate_key` are not provided in values, then a new CA  and a signed cert (signed by the new CA) are generated in the helm templates.

I will submit a PR later.

**Comment by armab** [comment]
We had HTTPS for st2web before, but after several discussions in the past moved away from this model.

The current way is to keep the st2web HTTP only, allowing users to rely on ingress controllers, load-balancers, and everything else to configure HTTPS on top of it.

Keeping the secure layer outside of the stackstorm-ha scope provides the separation of concerns and minimizes the amount of moving pieces and configuration. In K8s considering plenty of great solutions, it's something that's best configured and controlled outside of st2web.

**Comment by cognifloyd** [comment]
I went through all the git history and the related issues+PRs to understand the change to HTTP, and the conversation around it, before I worked on adding HTTPS support back in. Hopefully I didn't miss something.

I think there's a clean way to support both that offers a simple interface for chart users.
