### ISSUE TITLE
How do I change the YAML startup file if I use a separate MongoDB server

### ISSUE THREAD

**Issue by ShimingLee** [StackStorm/stackstorm-ha#286]
We purchased a standalone MongoDB.  We want to replace the MongoDB integration in stackStorm HA.  So what should I do?

**Comment by ShimingLee** [comment]
Yes I noticed this sentence in YAML, but where to configure the link address, is there a corresponding example?  thank you

**Comment by armab** [comment]
See:
https://docs.stackstorm.com/install/config/config.html#configure-mongodb
https://github.com/StackStorm/stackstorm-ha/blob/master/values.yaml#L65-L67
