### ISSUE TITLE
External mongodb setup problem

### ISSUE THREAD

**Issue by ShimingLee** [StackStorm/stackstorm-ha#287]
![图片](https://user-images.githubusercontent.com/22612182/155053324-2f568749-2b62-43ae-b556-dc0eefa8d800.png)

Must the database named ST2 be created before the service starts according to the above diagram?  Will the database be created automatically?  And what is the definition of this transport data type?

**Comment by armab** [comment]
You can omit the DB name if the MongoDB user you refer to in `st2.conf` has permissions to create a new DB in Mongo.

I'd recommend joining StackStorm Slack https://stackstorm.com/#community so you could use quick chat and get a faster help from the community.

**Comment by ShimingLee** [comment]
thank you
