### ISSUE TITLE
Customize pip versions

### ISSUE THREAD

**Issue by ShimingLee** [StackStorm/stackstorm-ha#295]
How to customize pip versions in StackStorm HA, or upgrade pip versions  ？

**Comment by cognifloyd** [comment]
pip is pinned in StackStorm itself. see:
https://github.com/StackStorm/st2/blob/master/Makefile#L59

The StackStorm HA helm chart does not create the docker images (or the debs used to install ST2 on those docker images), so this is not the right layer to change that aspect of StackStorm.

What seems to be the problem with the "pip versions in StackStorm HA"?

**Comment by cognifloyd** [comment]
I'm closing this for now. If there's something the chart needs to change to help you, then feel free to comment so we can discuss further.
