### ISSUE TITLE
Error during rancher deployment: failed to generate datastore_crypto_key (randBytes not defined)

### ISSUE THREAD

**Issue by rex** [StackStorm/stackstorm-ha#297]
I apologize that I didn't have the presence of mind to open this issue when I still had the error and stack trace in front of me, but I figured I'd at least open it in retrospect. 

Environment: `rancher@2.5.7`
Helm version: `3`
Chart version: `0.80.0`

### Problem
I didn't define `datastore_crypto_key` in `values.yaml` so it fell back to `conf/datastore_crypto_key.yaml`. For some reason it failed to generate the key, error message `randBytes is not defined`.

### Solution
I worked around it by generating it myself using `openssl rand -hex 32` and defining it in `datastore_crypto_key`.

Hopefully this helps someone!

**Comment by cognifloyd** [comment]
In order for the datastore_crypto_key generation to work, you need to use helm v3.5.0 (released January 2021) or newer.

The datastore_crypto_key generation was carefully crafted to match how StackStorm's `st2-generate-symmetric-crypto-key` script generates it.
If you can't use the helm-based generation, then please follow this section in the docs to generate a key:
https://docs.stackstorm.com/datastore.html#securing-secrets-admin-only

```
sudo st2-generate-symmetric-crypto-key --key-path datastore_key.json
```

And then put the contents of `datastore_key.json` in your values at `st2.datastore_crypto_key`.

NOTE: you should not need to run `openssl rand ...` to do this. `openssl rand ...` is incomplete and probably will not work in when StackStorm tries to load it to encrypt and decrypt keys.

You can do this on any ST2 installation, including in a [vagrant](https://github.com/StackStorm/st2vagrant) box.

-----
My notes from researching this:

Helm gets the `randBytes` function from the sprig library: https://masterminds.github.io/sprig/crypto.html#randbytes
Sprig got the `randBytes` function in v3.2.0 (from https://github.com/Masterminds/sprig/pull/253)
Helm v3.5.0 was the first version to use sprig v3.2.0: https://github.com/helm/helm/blob/v3.5.0/go.mod#L10
Helm v3.4.2 used sprig v3.1.0: https://github.com/helm/helm/blob/v3.4.2/go.mod#L10

**Comment by cognifloyd** [comment]
The minimum version is documented in the readme:
https://github.com/StackStorm/stackstorm-ha/blob/e4b72dc2162824a64ec8150d4e8362c39e645e29/README.md#L12-L14

**Comment by cognifloyd** [comment]
I'm closing this for now. If you were using v3.5 or greater, please reopen and let's diagnose further.
