### ISSUE TITLE
Issue creating installing packs

### ISSUE THREAD

**Issue by djh2020** [StackStorm/stackstorm-ha#42]
I am trying to install packs following the guide.  I enabled the K8 registry and I successfully created an image locally with a couple of public packs.  I am running into issues running the following command. 

```docker run --privileged --pid=host socat:latest nsenter -t 1 -u -n -i socat TCP-LISTEN:5000,fork TCP:docker.for.mac.localhost:5000```

I get the response ```Unable to find image 'socat:latest' locally```

How / where do I get this image from?

**Comment by armab** [comment]
@warrenvw Looks like the docs refer to invalid image.

@djh2020 Try using https://hub.docker.com/r/alpine/socat Docker image instead.

**Comment by warrenvw** [comment]
@djh2020  I apologize. This "local" image should never have been written into the documentation. I'll fix. In the meantime, you can use this workaround:

Create the following `Dockerfile`:

```
FROM alpine:3.8
RUN apk add --no-cache socat
CMD [ "socat" ] 
```

and build it using `docker build -t socat:latest .`

You should have no issues with this image using the command you listed above: 

`docker run --privileged --pid=host socat:latest nsenter -t 1 -u -n -i socat TCP-LISTEN:5000,fork TCP:docker.for.mac.localhost:5000`
