### ISSUE TITLE
Find resource Requests for all K8s pods/deployments

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#5]
> Moved from https://github.com/StackStorm/k8s-st2/issues/25

Find resource requests and resource limits (at least Memory) for each container/pod in StackStorm cluster, allow modifying the values.

This is the best K8s practice which affects cluster capacity planning and so is must do for prod and all Deployment objects we write.

Capacity planning is based on defined K8s resources metadata and so it's important setting to configure.
Another quick example if an app introduces memory leak or rabbitmq app acquires all the memory it can see. If such pods deployed to the cluster with no limit set they can crash a node.

### Components
- [x] st2client
- [x] st2web
- [ ] st2auth
- [ ] st2api
- [ ] st2stream
- [ ] st2rulesengine
- [ ] st2timersengine
- [ ] st2workflowengine
- [ ] st2notifier
- [ ] st2sensorcontainer
- [ ] st2actionrunner
- [ ] st2garbagecollector

### A few references

https://github.com/StackStorm/stackstorm-enterprise-ha/blob/9e3caf754b14f1a20efe45f43bc3037f9f09c649/templates/jobs.yaml#L95-L96

https://github.com/StackStorm/stackstorm-enterprise-ha/blob/9e3caf754b14f1a20efe45f43bc3037f9f09c649/values.yaml#L210-L216

**Comment by arms11** [comment]
@armab - I am interested in helping here. How do you proceed with this as resource limits will vary per individual needs. We have decent monitoring in place where i can observe consistent average of CPU/MEM usage by various pods. I am guessing we are interested in `resources` value = `minimum`. Bitnami charts recommend not to specify limits as it may create unwanted behavior or pod crash. Your thoughts?

**Comment by armab** [comment]
Yeah, you're right. We want the `spec.containers[].resources.requests` codified :+1:
