### ISSUE TITLE
Add some config value, so we can disable nginx ssl on st2web container

### ISSUE THREAD

**Issue by holyzhou** [StackStorm/stackstorm-ha#54]
when i deployment stackstorm-ha use k8s cluster,I find st2web accept ssl requests on 443 port. 
But in my case ,I just want use ingress controller handle ssl connection.
I'm always worried the ssl certificate will be expired, so I don't want put website certificate to Value.yaml and write to st2web container.
So, i'm curious, is possible stackstorm-ha offer extra config in helm value.yaml, that we can disable ssl certificate on  st2web container. 
Thinks anyway.

**Comment by armab** [comment]
Yes, we have an Ingress Controller planned in our roadmap.
See https://github.com/StackStorm/stackstorm-ha/issues/6 for more info which describes it in full.


From the description, seems we're on the same page about desired functionality, but adding your comment in https://github.com/StackStorm/stackstorm-ha/issues/6 won't hurt as it'll help to bring more attention to the problem.
