### ISSUE TITLE
Ability to replace "stanley" ssh remote user by a custom account

### ISSUE THREAD

**Issue by isilverwood** [StackStorm/stackstorm-ha#56]
In the current Helm chart for stackstorm-ha, it is impossible via values.yaml to replace the default system user "stanley" that is used to connect to remote servers.

This would need to be modified via values.yaml.

**Comment by armab** [comment]
Thanks! This is a reasonable feature request :+1: 
Originally, for simplicity default `stanley` user is created during the rpm/deb packages.

For custom `system_user` (specified via Helm values and in st2.conf), we'll need to execute linux user creation at K8s deployment bootstrap time as this is something not pre-baked in Docker images. This operation probably needs to be done only for `st2actionrunner` container.

-----

As a workaround per https://docs.stackstorm.com/troubleshooting/ssh.html it's possible to specify user directly when running `core.remote`:

```
st2 run core.remote cmd=whoami hosts=localhost username=test_user private_key=/home/stanley/.ssh/stanley_rsa
```

**Comment by cognifloyd** [comment]
I have to change the user as well, along with several other changes (eg extra system dependencies needed by some actions). So, I'll be building a custom docker image with those changes.

Once I do that, I'll circle back here and report on what changes are need in the helm chart to support a non-stanley `system_user` that is baked into the docker image.

**Comment by cognifloyd** [comment]
Oh. I forgot about this issue, so I filed #208 and then added this in PR #220. So, I'm going to close this since #220 is merged now.

You'll need to use a custom st2actionrunner image that includes your user, and then change `st2.system_user.user` in values.
