### ISSUE TITLE
Basic Helm Chart end to end sanity tests

### ISSUE THREAD

**Issue by Kami** [StackStorm/stackstorm-ha#59]
This issue brought up lack of even basic end to end sanity tests - #57.

To begin with, I think having even basic tests which spin up all the services and just run ``st2 run core.local cmd=date ; st2 run pack install foo`` or similar (aka what we do on Travis for StackStorm packages) would help a lot and catch such issues early on.

If you think this belongs to the Integration tests issue (https://github.com/StackStorm/stackstorm-ha/issues/27) feel free to merge those two issues and close this one.

And down the road, having CICD running using Helm Charts will help a lot as well.

**Comment by armab** [comment]
Yeah, I believe it adds +1 reason to https://github.com/StackStorm/stackstorm-ha/issues/27
