### ISSUE TITLE
etcd deployment is unstable

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#75]
We're using external chart dependency https://github.com/helm/charts/tree/master/incubator/etcd from Helm incubator to deploy `etcd` cluster as part of the `stackstorm-ha`.

It doesn't work well, failing frequently, like https://circleci.com/gh/StackStorm/stackstorm-ha/604.

Example K8s pod list:
```
NAME                                                              READY   STATUS             RESTARTS   AGE
st2cicd-etcd-0                                                    0/1     CrashLoopBackOff   107        9h
st2cicd-etcd-1                                                    1/1     Running            0          11h
st2cicd-etcd-2                                                    1/1     Running            112        9h
```

With error log from `etcd` pod:
```
Waiting for st2cicd-etcd-2.st2cicd-etcd to come up
Re-joining etcd member
cat: can't open '/var/run/etcd/member_id': No such file or directory
```

Research other solutions, consider `etcd` operator and how to automate that via Helm deployment.

**Comment by trstruth** [comment]
What does this imply for the stackstorm deployment as a whole?  Is it simply that the etcd cluster is operating with one replica down?

**Comment by armab** [comment]
Sometimes with two blinking nodes, which is worse and likely lead to coordination issues.

**Comment by armab** [comment]
If someone wants to help with this, - next step would be looking at https://github.com/helm/charts/tree/master/stable/etcd-operator as a replacement to existing unstable one https://github.com/helm/charts/tree/master/incubator/etcd

**Comment by armab** [comment]
Based on https://github.com/StackStorm/stackstorm-ha/pull/81, https://github.com/helm/charts/tree/master/stable/etcd-operator has chicken-and-egg issues when we can't rely on it as a dependency, because custom resource definition `EtcdCluster` that actually creates a cluster is not registered/available at `helm install` time.

cc @warrenvw you might be interested.

**Comment by armab** [comment]
Next stop: https://github.com/bitnami/charts/tree/master/bitnami/etcd which looks like well maintained.
