### ISSUE TITLE
RabbitMQ custom st2packs are not working on 3.2dev version

### ISSUE THREAD

**Issue by ratnakarreddyg** [StackStorm/stackstorm-ha#83]
I have created a custom docker st2pack for RabbitMQ to install in Stackstorm-HA environment on the version 3.2Dev(Yes I have passed rabbitmq.yaml file by modifying in the values.yaml file and executed helm upgrade). However, this RabbitMQ is not showing on my server. 

Followed the same process on version 3.1Dev and the connection status is showing as running on my RabbitMQ server console.

**Comment by armab** [comment]
Are you referring to https://github.com/stackstorm-exchange/stackstorm-rabbitmq pack?
What logs is showing `job-st2-register-content` K8s job?

**Comment by cognifloyd** [comment]
@ratnakarreddyg are you still having this issue? Have you tried on any newer st2 versions?

This has been tagged with "needs more info" for awhile - if this is resolved, can we close this issue?

**Comment by cognifloyd** [comment]
There has been no recent response, so I'm going to assume that this has been resolved in newer pack, chart, or st2 versions.

If you are still having issues between your st2actionrunner pods and RabbitMQ, please add some more info and reopen this. Thanks!
