### ISSUE TITLE
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by tonysyzer69** [StackStorm/stackstorm-ha#85]
go the error when trying to install stackstorm in K8S cluster, V1.6.

Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

Command to install stackstorm-ha:
helm repo add stackstorm https://helm.stackstorm.com/
helm install stackstorm/stackstorm-ha

**Comment by armab** [comment]
To help isolating this issue, can you try to run the same chart in K8s `v1.5` and see if it's reproducible in that version?

**Comment by armab** [comment]
The issue was coming from the `rabbitmq-ha` 3rd party Helm chart dependency.
Fixed in #100, see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more info.
