### ISSUE TITLE
st2-register-content job should clean up packs/actions/etc that no longer exist

### ISSUE THREAD

**Issue by Xelinor** [StackStorm/stackstorm-ha#93]
Right now, the functionality of the HA-implementation makes it so that custom packs are installed via Docker image. This works fine and is in line with expected results.

What doesn't work as _expected_ is the removal of those packs and actions. Removing a pack/action/rule/etc from the docker container leaves it showing in the list even though it will not function when called. This is because no cleanup step is performed to remove those packs.

I would propose that an expected behavior would be that any functionality not defined in values.yaml or else by the docker container would be reasonable to assume to be overridden. This is especially confirmed by the warning message displayed when connecting to the st2client pod.

**Comment by armab** [comment]
This logic is not `stackstorm-ha` Helm chart responsibility, but how StackStorm pack management works.
Please submit a report/feature request in https://github.com/stackstorm/st2 instead.

Thanks!

**Comment by armab** [comment]
After a quick search there looks like a lot of issues in st2 reported already:

- https://github.com/StackStorm/st2/issues/3143
- https://github.com/StackStorm/st2/issues/3016
- https://github.com/StackStorm/st2/issues/3143
- https://github.com/StackStorm/st2/issues/924
- https://github.com/StackStorm/st2/issues/3313

Closing in favor of those.

**Comment by manisha-tanwar** [comment]
Hi @armab I agree with what you mentioned here but even if we modify existing action pack stackstorm-ha isn't reflecting it. I had to delete the instance and create it again in order to reflect changes. That's not the case with st2.
