### ISSUE TITLE
Migrate to Helm 3.0 (2.x deprecation in November 2020)

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#98]
Helm `v3.0` GA was released in Nov 2019 https://helm.sh/blog/helm-3-released/

While at the moment we'd prefer to pin Helm `2.x`, consider migrating to `3.x` when it'll stabilize a little bit and see what involves for us to rely on latest Helm.

**Comment by rahulparihar270992** [comment]
Hi @armab , hope you are doing well ? As you have added migrate to helm 3.0 feature for stackstorm . Do you have any initial thoughts how you are going to take it forward ? If i am correct i have made change in https://github.com/StackStorm/stackstorm-ha/blob/master/.circleci/config.yml#L20 file to point helm version 3.0.0 . but still getting issue as 
helm install stackstorm-ha/ --generate-name
**Error: found in Chart.yaml, but missing in charts/ directory: rabbitmq-ha, mongodb-replicaset, external-dns, etcd-operator**  Do you have any points for this?

**Comment by armab** [comment]
These are 3rd party Helm charts from https://github.com/helm/charts/blob/master/stable/

From the message above, looks like in order to switch to Helm `3.0` those upstream dependencies needs to be migrated first.
See https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/Chart.yaml#L2 which still references previous Helm API Version.

**Comment by wantdrink** [comment]
Hi @armab, I installed rabbitmq-ha-1.36.4 first with helm 3.0 and it succeeded:

> NAMESPACE     NAME                                  READY   STATUS             RESTARTS   AGE     IP                
> default       my-rabbit-rabbitmq-ha-0               1/1     Running            1          2d8h    10.244.3.29      
> default       my-rabbit-rabbitmq-ha-1               1/1     Running            1          2d8h    10.244.1.24       
> default       my-rabbit-rabbitmq-ha-2               1/1     Running            1          2d8h    10.244.2.14    

  

So does it mean this chart works in helm 3.
But if install ss ha with :
helm install stackstorm -n st2 -f values.yaml .

The error is:

> manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"

**Comment by armab** [comment]
That part is coming from the "etcd-operator" Helm chart dependency from the official Helm repository.

Relevant answer from similar https://github.com/kubernetes-sigs/kubefed/issues/1143#issuecomment-528992390:
![](https://user-images.githubusercontent.com/16505634/64456503-f768a880-d0b5-11e9-8b7c-2b3efb316408.png)

**Comment by wantdrink** [comment]
@armab  Thanks. So the left is etcd-operator's issue. Let's wait for it to be updated to support helm 3.

**Comment by rahulparihar270992** [comment]
> These are 3rd party Helm charts `stackstorm-ha` relies on https://github.com/helm/charts/blob/master/stable/
> 
> From the message above, looks like in order to switch to Helm `3.0` those upstream dependencies needs to be migrated first.
> See https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/Chart.yaml#L2 which still references previous Helm API Version.

Thanks @armab and @wantdrink for replying back . have tried to make changes in https://github.com/rahulparihar270992/charts  repo as belows https://github.com/rahulparihar270992/charts/blob/master/stable/rabbitmq-ha/Chart.yaml#L2 . and tried to changed requirements.yml as https://github.com/rahulparihar270992/stackstorm-ha/blob/feature/stackstome-v1/requirements.yaml#L4 . Not sure this is the right pointing to stable dependencies ? Do you have any suggestion how it going to work?  Still facing similar issue.
**Error: found in Chart.yaml, but missing in charts/ directory: rabbitmq-ha, mongodb-replicaset, external-dns, etcd-operator**

**Comment by armab** [comment]
I hadn't chance to really try Helm 3.0 yet, so google is your better friend than me here.

However looks like the first big visible difference between `v2` and `v3` is that requirements should be moved to `Chart.yml` instead of `requirements.yml` file.

**Comment by rahulparihar270992** [comment]
> Hi @armab, I installed rabbitmq-ha-1.36.4 first with helm 3.0 and it succeeded:
> 
> > NAMESPACE     NAME                                  READY   STATUS             RESTARTS   AGE     IP
> > default       my-rabbit-rabbitmq-ha-0               1/1     Running            1          2d8h    10.244.3.29
> > default       my-rabbit-rabbitmq-ha-1               1/1     Running            1          2d8h    10.244.1.24
> > default       my-rabbit-rabbitmq-ha-2               1/1     Running            1          2d8h    10.244.2.14
> 
> So does it mean this chart works in helm 3.
> But if install ss ha with :
> helm install stackstorm -n st2 -f values.yaml .
> 
> The error is:
> 
> > manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
> > Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"


@wantdrink , @armab  I am also facing similar issue . Have you updated helm chart for etcd-operator ?
Can you please give me some pointer here, what next step have you taken?

**Comment by wantdrink** [comment]
@rahulparihar270992 SS chart has a set of dependencies chart. Fortunately some of them already supports Helm3.
unfortunately etcd-operator as one mandatory dependency cannot be omitted and must be installed. But its chart hasn't been updated yet for Helm3.0 (version 0.10.0 in requirement).
Let me try 0.10.2 today and see if it works.

**Comment by wantdrink** [comment]
@armab  Thanks, you are right.

**Comment by wantdrink** [comment]
0.10.2 can be installed with helm3. It looks like we can move forward.

**Comment by armab** [comment]
Sounds promising.
Can you guys create a PR to address that?

**Comment by wantdrink** [comment]
Hi @armab I'd like to do that. I'm still testing today with outside rabibtmq & mongo instead of installing them with ss chart.
Now I pods/services/statefulset/ep are created successfully, login portal/cli/default pack action running all good.
But I still have some questions:

1. There is still "crd-install" warning but it seems ss works well. Could you please guide us for how to validate if etcd cluster works well together with ss? Maybe some simple testing is needed.

2. I want to put ss images into my private repository, in that way I can deploy my own pack image to test, also to faster the deployment. I added repository in values.yml as below but it doesn't work.

```
image:
  repository: repository.test.com:8443/stackstorm
  pullPolicy: IfNotPresent

```

Then I changed templates/_helpers.tpl as:
```
# Generate Docker image repository: Private 'docker.stackstorm.com' for Enterprise vs Public Docker Hub 'stackstorm' for FOSS version
{{- define "imageRepository" -}}
{{- if required "Missing context '.Values.enterprise.enabled'!" .Values.enterprise.enabled -}}
docker.stackstorm.com
{{- else -}}
repository.test.com:8443/stackstorm
{{- end -}}
{{- end -}}
```

It didn't work either and images were stilled pulled from docker hub.

3. The same with item 2 how can I change the default repository of etcd-operator?
I changed the stackstorm-ha/charts/etcd-operator/values.yaml and it didn't work.
E.G.
```
# etcdOperator
etcdOperator:
  name: etcd-operator
  replicaCount: 1
  image:
    repository: repository.test.com:8443/quay.io/coreos/etcd-operator
    tag: v0.9.4
    pullPolicy: IfNotPresent
  resources:
    cpu: 100m
    memory: 128Mi

```

**Comment by armab** [comment]
Some of StackStorm services will just fail if they couldn't contact `etcd` for coordination.
For using custom st2 packs, see: https://github.com/StackStorm/stackstorm-ha#install-custom-st2-packs-in-the-cluster and https://docs.stackstorm.com/install/k8s_ha.html#custom-st2-packs.

You can ask other questions in StackStorm Community: https://stackstorm.com/#community Slack or Forum.
Let's please keep this issue dedicated to Helm `v3.0`.

**Comment by wantdrink** [comment]
Thanks @armab 
Find the root cause. I used tgz file for command helm install and the image repository of ss/etcd cannot be changed by passing the values.yaml. 
To solve this just modify the _helper and charts/etcdxxx/values.yml of tgz file then rerun and finally the helm pull images from my private repository.

**Comment by wantdrink** [comment]
@armab  I've tested the installation of etcd-operator 0.10.2. There is an error when executing helm install but everything can be installed successfully.
Also I tested ss feature and it looks good.

Finally I rebooted all k8s nodes and there is an issue: the etcd cluster pods cannot be restarted automatically:

```
default       etcd-cluster-6255djfdkq                              0/1     Completed          0          17m     <none>          
default       etcd-cluster-k5lmchwjp5                              0/1     Completed          0          16m     <none>          
default       etcd-cluster-nlzjt5qmdn                              0/1     Completed          0          17m     <none> 
```

I have to restart them manually and after that ss works well.

**Comment by armab** [comment]
Good to hear.

BTW `Etcd` issue you mentioning is not really related to Helm 3.0. We have it documented here: https://github.com/StackStorm/stackstorm-ha/issues/94

**Comment by wantdrink** [comment]
@armab  hum......maybe single etcd instance is better. 
Thanks.

**Comment by erenatas** [comment]
> Hi @armab, I installed rabbitmq-ha-1.36.4 first with helm 3.0 and it succeeded:
> 
> > NAMESPACE     NAME                                  READY   STATUS             RESTARTS   AGE     IP
> > default       my-rabbit-rabbitmq-ha-0               1/1     Running            1          2d8h    10.244.3.29
> > default       my-rabbit-rabbitmq-ha-1               1/1     Running            1          2d8h    10.244.1.24
> > default       my-rabbit-rabbitmq-ha-2               1/1     Running            1          2d8h    10.244.2.14
> 
> So does it mean this chart works in helm 3.
> But if install ss ha with :
> helm install stackstorm -n st2 -f values.yaml .
> 
> The error is:
> 
> > manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
> > Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"

It seems like I am late to this conversation but I have managed to find a workaround to this problem which was to install etcd operator manually before installing stackstorm-ha. Currently I can run Stackstorm without any issues. 

But I must say that, Helm's error traces are just awful. It says there is an issue but does not say about where the problem is...

**Comment by Fauli** [comment]
Do you have an eta for the migration of the charts to helm 3?
Or is there some repo available that has the adopted files?
@wantdrink your example with external components would be very nice and helpful.

Thanks a lot!

**Comment by armab** [comment]
There is no ETA for migrating to Helm 3, but we’ll be happy to accept PR contributions.

**Comment by Fauli** [comment]
Is there some progress to build upon available or does one have to start from the helm 2 charts?

**Comment by armab** [comment]
You can read this Issue history with the pointers regarding Helm 2 migration.

**Comment by mbrowne** [comment]
Version 0.10.2 no longer exists for some reason (0.10.1 doesn't exist either). But version 0.10.0 can still be downloaded. I haven't gotten it to install yet locally though with helm 3...not sure if it has something to do with Docker Desktop (which is how I'm running K8s) or something else...

**Comment by c1505** [comment]
have people had success with helm v3 ?

**Comment by wantdrink** [comment]
@Fauli  @c1505 
The simplest way to install with helm3(currently) is to clean the dependencies of requirements.yaml and then define the db/message/coordinator url etc in the values.yaml. Of course these dependencies should be installed separately before installing ss ha.

@armab another simple question: if we want to specify the ssl key/cert file like below, where should we put these files? 

```
.......
st2:
  config: |
    ......

    [database]
    host = 192.168.112.71
    ssl = True
#    ssl_keyfile = <Path to key file>
#    ssl_certfile = <Path to certificate>
#    ssl_cert_reqs = <One of none, optional or required>
#    ssl_ca_certs = <Path to certificate form mongod>
#    ssl_match_hostname = <True or False>
```

Thanks.

**Comment by armab** [comment]
@wantdrink You need to find the way to share these files with all the Pods.
Existing SSH key in Helm values and following that in Helm templates/source code can give some pointers as an example where to look at.

**Comment by wantdrink** [comment]
Thanks a lot @armab

**Comment by armab** [comment]
https://helm.sh/blog/helm-v2-deprecation-timeline/

**Comment by arms11** [comment]
Hi all, I know I am a bit late to this thread, but I have been running StackStorm-HA deployment using Helm 3 from the day 1 in our production and have not come across any issue that's blocker. 

```kubectl get pods
NAME                                                              READY   STATUS      RESTARTS   AGE
etcd-cluster-6qkcrbvm2r                                           1/1     Running     0          76d
etcd-cluster-xzkpsw74rx                                           1/1     Running     0          76d
etcd-cluster-zh4gjj2skm                                           1/1     Running     0          76d
etcd-operator-etcd-operator-etcd-backup-operator-7766cf9488dmxn   1/1     Running     2          76d
etcd-operator-etcd-operator-etcd-operator-56dfc86b9d-pqrd4        1/1     Running     4          76d
etcd-operator-etcd-operator-etcd-restore-operator-c564466bbbpbj   1/1     Running     2          76d
st2ha-etcd-operator-etcd-operator-5fc86f779d-6jh5q                1/1     Running     0          76d
st2ha-job-st2-apikey-load-29mh5                                   0/1     Completed   0          6d15h
st2ha-job-st2-key-load-2mp95                                      0/1     Completed   0          6d15h
st2ha-job-st2-register-content-bpqfw                              0/1     Completed   0          6d15h
st2ha-mongodb-ha-0                                                1/1     Running     0          76d
st2ha-mongodb-ha-1                                                1/1     Running     0          76d
st2ha-mongodb-ha-2                                                1/1     Running     0          76d
st2ha-rabbitmq-ha-0                                               1/1     Running     1          39d
st2ha-rabbitmq-ha-1                                               1/1     Running     4          76d
st2ha-rabbitmq-ha-2                                               1/1     Running     3          76d
st2ha-st2actionrunner-58c5bb6946-8b6g2                            1/1     Running     0          6d15h
st2ha-st2actionrunner-58c5bb6946-czpt9                            1/1     Running     0          6d15h
st2ha-st2actionrunner-58c5bb6946-g56cg                            1/1     Running     0          6d15h
st2ha-st2actionrunner-58c5bb6946-m7hxr                            1/1     Running     0          6d15h
st2ha-st2actionrunner-58c5bb6946-v9975                            1/1     Running     0          6d15h
st2ha-st2api-789578f8f5-cqbxx                                     1/1     Running     0          6d15h
st2ha-st2api-789578f8f5-dl5bn                                     1/1     Running     0          6d15h
st2ha-st2auth-76b46895b-hp9w6                                     1/1     Running     0          6d15h
st2ha-st2auth-76b46895b-qp48j                                     1/1     Running     0          6d15h
st2ha-st2client-6467866ddc-57td8                                  1/1     Running     0          6d15h
st2ha-st2garbagecollector-5599b58cb6-4qmxx                        1/1     Running     0          18d
st2ha-st2notifier-55b9c595c8-2glxh                                1/1     Running     0          18d
st2ha-st2notifier-55b9c595c8-7zz8m                                1/1     Running     0          18d
st2ha-st2rulesengine-7d858458bf-cw92d                             1/1     Running     0          18d
st2ha-st2rulesengine-7d858458bf-r5t7g                             1/1     Running     0          18d
st2ha-st2scheduler-6985f84c9c-84sdr                               1/1     Running     0          18d
st2ha-st2scheduler-6985f84c9c-hq6rq                               1/1     Running     0          18d
st2ha-st2sensorcontainer-6855744bf-tcxf7                          1/1     Running     0          6d15h
st2ha-st2stream-7867fc988f-bhk5p                                  1/1     Running     0          18d
st2ha-st2stream-7867fc988f-nwpfm                                  1/1     Running     0          18d
st2ha-st2timersengine-69d47748b8-ppmt2                            1/1     Running     0          18d
st2ha-st2web-74b7548b66-txjbn                                     1/1     Running     0          76d
st2ha-st2web-74b7548b66-wsvhl                                     1/1     Running     0          76d
st2ha-st2workflowengine-6bc99758fd-r2cnt                          1/1     Running     0          18d
st2ha-st2workflowengine-6bc99758fd-vpsd8                          1/1     Running     0          18d```

Below is the helm client version running on my machine from where I deployed the app. The same was present in our Bamboo agent.
```helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}```

I am not sure about any specifics but so far this has been running fine for 2+ months. I have 2 different clusters in AWS using EKS.

**Comment by christopher-russell** [comment]
Hi everyone, I have raised PR https://github.com/StackStorm/stackstorm-ha/pull/163 in an attempt to move this issue along to completion. I have tested it in a few environments with helm v3.4.1 seems to work.
